version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./project:/var/www/html
      - ./_docker/nginx/etc/hosts:/etc/hosts
      - ./_docker/logs/nginx:/var/log/nginx
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    links:
      - app
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./project:/var/www/html
      - ./_docker/logs/app:/var/log
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./_docker/db/mysql:/var/lib/mysql
      - ./_docker/logs/mysql:/var/log/mysql
      - ./_docker/db/mysql-files:/var/lib/mysql-files
      - ./_docker/db/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    ports:
      - 3306:3306
    container_name: project_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8082:80
    environment:
      - PMA_HOST = db
      - PMA_USER = root
      - PMA_PASSWORD = root
    container_name: project_phpmyadmin